name: Build AppImage CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Install required dependencies
      run: sudo apt install -y gtk-update-icon-cache python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse
    
    - name: Download AppImageBuilder etc.
      run: |
        mkdir -p ~/.local/bin
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O ~/.local/bin/appimagetool
        chmod +x ~/.local/bin/appimagetool
        pip3 install appimage-builder
    
    - name: Build AppImage
      run: |
        sed -i "s/BUILD_INFO = .*/BUILD_INFO = 'Official AppImage by DavidoTek'/" pupgui2/constants.py
        sed -i "s/PySide6.*/PySide6==6.2.4/" requirements.txt
        appimage-builder

    - name: Upload AppImage
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          ./ProtonUp-Qt*.AppImage*
