name: Build AppImage CI

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27

    - name: Build AppImage
      run: |
        sed -i "s/BUILD_INFO = .*/BUILD_INFO = 'Official AppImage by DavidoTek'/" pupgui2/constants.py
        nix build .#appimage --impure

    - name: Prepare AppImage for upload
      run: |
        version=$(grep -oP "APP_VERSION = '\K[^']+" pupgui2/constants.py)
        cp result "ProtonUp-Qt-${version}-x86_64.AppImage"

    - name: Upload AppImage to release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ProtonUp-Qt-*.AppImage

    - name: Upload AppImage as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProtonUp-Qt
        path: ProtonUp-Qt-*.AppImage
        if-no-files-found: error
